### PR TITLE
Issue/#180 add spring profile

### PR DESCRIPTION
**Pull request by razine-bensari**
# Related Issue
- #180 

# Proposed changes
- addition of multiple properties file, configured to be passed via command line when starting the app locally

We can now use those command to run the app locally with the given spring profil:

mvn spring-boot:run -Dspring.profiles.active=prod
mvn spring-boot:run -Dspring.profiles.active=local
mvn spring-boot:run  (uses dev db)

# Checklist (if applicable)
non applicable

TO BE MERGED AFTER PR #218 

# Reviewer(s)
 - @wltrf 
 - @abdulmansour 
 - @DPigeon

### CODE REVIEW

**Comment by razine-bensari** [comment]
The two security hotspot by sonarcloud are related to front end, Ill open a ticket for it

**Comment by DPigeon** [comment]
In addition, I think we'll need to modify the backend Dockerfile and pass the proper argument from the CD in the CMD:
```
CMD ["java", ${profile} "-jar", "/home/maven/jar/moneytree.jar"]
```

depending on if on uat or prod. Cause right now it will take the prod database on uat and prod. So what we want is to detect the branch from where the CD is being executed (uat or master) and pass the argument to the backend dockerfile being nothing if uat and ```-Dspring.profiles.active=prod``` if prod.

**Comment by razine-bensari** [comment]
> In addition, I think we'll need to modify the backend Dockerfile and pass the proper argument from the CD in the CMD:
> 
> ```
> CMD ["java", "${profile}", "-jar", "/home/maven/jar/moneytree.jar"]
> ```
> 
> depending on if on uat or prod. Cause right now it will take the prod database on uat and prod. So what we want is to detect the branch from where the CD is being executed (uat or master) and pass the argument to the backend dockerfile being nothing if uat and `-Dspring.profiles.active=prod` if prod.

Indeed, Ill update the PR and update the docker file

**Review by DPigeon — APPROVED** [review]
Nice work on the CD edits!

**Comment by razine-bensari** [comment]
> Nice work on the CD edits!

I did that with you ahahah

**Comment by DPigeon** [comment]
> > Nice work on the CD edits!
> 
> I did that with you ahahah

I know but still haha

**Pull request merged**
