### PR TITLE
#114: Enable TLS on Both Environments

### PR DESCRIPTION
**Pull request by DPigeon**
# Related Issue
- #114 

# Proposed changes
- Creation of SSL certificates when building our client Dockerfile
- Nginx listens on port 443 by taking the proper certificate keys localted at `ssl/` directory within the image
- Nginx also redirects any http requests to https requests
- Tested locally & on dev environment (see picture below)

# Additional Info
- We should now be able to see that both environments are secure with certificates created with the SHA-256 algorithm. 

# Screenshots
Tested locally with a local deployment:
localTest

Tested on UAT environment:
testUAT

# Reviewer(s)
 - @Alessandro100 
 - @razine-bensari

### CODE REVIEW

**Comment by Alessandro100** [comment]
@DPigeon is there a way to test this before it going into dev?

**Comment by DPigeon** [comment]
> @DPigeon is there a way I can test this on my end?

Yes this was my next step. However, I tried testing directly on the dev VM for other devops related stories before and we could not do it due to the fact that our docker daemon exceeds maximum memory when building the frontend or backend. 
Now that we're using a swap file to balance the memory, I will attempt this test again tonight. I'll keep you updated. 

Testing it locally on my machine is a sufficent test. However things can break in prod so I hope to be able to test it on the VMs.

**Comment by DPigeon** [comment]
Update: I haven't had any luck when testing on the uat env. When accessing the UAT environment right now, our certificate is not trusted so I will have to generated a trusted one. This will take more investigating than I thought since we have an additional layer (Nginx) in production when we deploy.

**Comment by razine-bensari** [comment]
> Update: I haven't had any luck when testing on the uat env. When accessing the UAT environment right now, our certificate is not trusted so I will have to generated a trusted one with certbot or another tech that provides trustes certs. This will take more investigating than I thought since we have an additional layer (Nginx) in production when we deploy.
> 
> I'll keep this pull request open and work here. Most changes are made on the VM by executing openssl or certbot commands.

Just finished reviewing, nice work @DPigeon 

Let me know if there is anything I can do to help. Perhaps we need certificate providers for UAT and PROD ?

**Comment by DPigeon** [comment]
> > Update: I haven't had any luck when testing on the uat env. When accessing the UAT environment right now, our certificate is not trusted so I will have to generated a trusted one with certbot or another tech that provides trustes certs. This will take more investigating than I thought since we have an additional layer (Nginx) in production when we deploy.
> > I'll keep this pull request open and work here. Most changes are made on the VM by executing openssl or certbot commands.
> 
> Just finished reviewing, nice work @DPigeon
> 
> Let me know if there is anything I can do to help. Perhaps we need certificate providers for UAT and PROD ?

Yeah I will give it a try with Let's Encrypt or Certbot.

**Comment by DPigeon** [comment]
@Alessandro100 @razine-bensari I was able to create a successful build with trusted certificates. They expire in 90 days (around April 14th) so I will create an alert to renew them on time before that. We're using Let's Encrypt with certbot certificates. 

Tested on UAT environment. Ready for official review!

**Review by razine-bensari — APPROVED** [review]
Nice work!!!!

**Pull request merged**
