### PR TITLE
Feature/#269 additional stock information

### PR DESCRIPTION
**Pull request by marwan-ayadi**
# Related Issue
#269 

# Proposed changes
- Add three mat-card ( followers - top investors -People who owns this stock also own these stocks) UI

# Additional Info
- using fake data for the moment

# Reviewer(s)
 @EspressoCode

### CODE REVIEW

**Comment by EspressoCode** [comment]
Good job on this story, I left you a couple of comments, mainly on styling.

**Comment by EspressoCode** [comment]
Please see the screenshots and each label to find out about the requested change:
A: Based on our Figma design, the spacing between the cards should be increased. 
B: Font weight should be increased, the color should be changed to $mt-dark.
C: The icons labelled C are different in our design, also the color should be darker.
D: This has to be the list of other stocks (TD, TSLA, etc).

more stock info


E: For mobile ver, kindly consider aligning the cards to the center.

mobile

**Review by EspressoCode — CHANGES_REQUESTED** [review]
Please see the screenshots and each label to find out about the requested change:
A: Based on our Figma design, the spacing between the cards should be increased.
B: Font weight should be increased, the color should be changed to $mt-dark.
C: The icons labelled C are different in our design, also the color should be darker.
D: This has to be the list of other stocks (TD, TSLA, etc). Also the color on our design is different ($mt-dark again)

more stock info


E: For mobile ver, kindly consider aligning the cards to the center.

mobile

**Review by EspressoCode — APPROVED** [review]

**Comment by marwan-ayadi** [comment]
PR comments resolved

**Pull request merged**
