### PR TITLE
code smells minor and critical

### PR DESCRIPTION
**Pull request by arthur-del**
# Related Issue
- Reduce code smells

# Proposed changes
- Tackled unassigned minor code smells
- Tackled unassigned critical code smells

# Additional Info
- Creating this PR early to see the branch on SonarCloud to see progress

### CODE REVIEW

**Review by Alessandro100 — COMMENTED** [review]
Hey I noticed that instead of deleting the empty constructors / empty functions you added comments to them is there a reason you did that vs deleting them?

**Comment by DPigeon** [comment]
Hey guys is there an issue for this?

**Comment by arthur-del** [comment]
> 
> 
> Hey I noticed that instead of deleting the empty constructors / empty functions you added comments to them is there a reason you did that vs deleting them?

Depending on the case it would throw an error. Out of consistency and by fear of breaking stuff I took the option that satisfied sonarcloud without impacting the code.

**Review by Alessandro100 — APPROVED** [review]
nice changes

**Pull request merged**
