### PR TITLE
#154 ci improvements

### PR DESCRIPTION
**Pull request by wltrf**
# Related Issue
- #154 

# Proposed changes
- Split ci.yml into 2 files: ci_frontend.yml and ci_backend.yml
- Single step which calls `mvn clean verify` for backend instead of many redundant repetitive and slow
- use mvn (binary) instead of ./mvnw (wrapper)
- run ci on push to dev and master so we get sonarcloud scan for those branches without having to do manually
- some minor cache handling redundencies and extra unecessary npm install step removed
- use npm ci instead of npm i see [here](https://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable)

# Additional Info
- ci_frontend will run when any change in client/**
- ci_backend will run when any change in backend/**

# Reviewer(s)
 - @DPigeon 
 - @Alessandro100

### CODE REVIEW

**Comment by wltrf** [comment]
here we can see that a change in the /backend folder triggered the CI Backend Pipeline only and a single sonarcoud bot comment was registered.
Screenshot from 2020-11-27 14-13-37

**Comment by wltrf** [comment]
here we see that changes in both frontend and backend will result in both ci pipelines to trigger with two comments from the sonarcloud both just as before.
Screenshot from 2020-11-27 14-22-30

**Comment by wltrf** [comment]
similarly to backend, if theres a change only on frontend, only the frontend ci pipeline will run
Screenshot from 2020-11-27 14-33-32

**Comment by wltrf** [comment]
Now, the only issue is when we don't have any changes in either ./backend or ./client, the checks will wait and never be fulfilled (note the lack of a check mark/yellow circle/red circle next to the verified label). A workaround is to modify the readme in backend or client with a minor change that doesn't have any impact like a space.
Screenshot from 2020-11-27 14-51-12

**Comment by wltrf** [comment]
This last commit reflect the workaround explained in the previous comment. (see the yellow circle now ;) )
Screenshot from 2020-11-27 14-56-04

**Review by Alessandro100 — APPROVED** [review]
Looks good to me, nice changes. One small note is when making a branch name just format it to our convention
issue/...
feature/....
bug/...

other than that it's good to go

**Pull request merged**
