### PR TITLE
Refactoring/#209 fix security hotspots in the frontend

### PR DESCRIPTION
**Pull request by EspressoCode**
# Related Issue
- Refactored frontend to resolve code smells.
- Reviewed the security hotspots for frontend

### CODE REVIEW

**Comment by DPigeon** [comment]
Change the destination branch to dev please and I`ll review afterwards.

**Comment by EspressoCode** [comment]
> Change the destination branch to dev please and I`ll review afterwards.

I changed it to dev.

**Review by DPigeon — COMMENTED** [review]
This looks good to me. I'll wait for Alessandro for final approval.

**Review by Alessandro100 — APPROVED** [review]
Looks fair, I know this is a lot of small fixes, but it will keep our code cleaner and it's good to refactor every once in awhile

**Pull request merged**
