### PR TITLE
Add https backend #250

### PR DESCRIPTION
**Pull request by wltrf**
# Related Issue
- #250 

# Proposed changes
- Add https in backend (@wltrf)
- Change frontend to use https instead of http when calling backend (@Alessandro100)

# Reviewer(s)
 - @Alessandro100 
 - @razine-bensari 
 - @DPigeon

### CODE REVIEW

**Comment by wltrf** [comment]
Only missing @Alessandro100's part

**Review by Alessandro100 — APPROVED** [review]
On my side it works, nice stuff. Just confirm that localhost is permanently https. If so merge it, and I'll change the settings on Alpaca (redirect)

**Comment by wltrf** [comment]
fixed localhost so that it doesnt require https, good to go on my end.

**Comment by DPigeon** [comment]
Let me know when this is ready to review. I see it marked as a draft now.

**Review by razine-bensari — APPROVED** [review]
Thankl you!

**Pull request merged**
